require("Kiran.keymaps")
require("Kiran.plugins")
require("Kiran.cmp")
require("Kiran.treesitter")
require("Kiran.telescope")
require("Kiran.lsp")
require("Kiran.gitsigns")
require("Kiran.neovide")
require("Kiran.options")
require("Kiran.comment")

vim.cmd([[ let g:netrw_banner=0 ]])
vim.cmd([[ colorscheme dracula ]])
